import type { Route as _IndexRoute } from '../pages/';
/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import type { Route as _DesignsRoute } from '../pages/designs';
import type { Route as _EditorRoute } from '../pages/editor';
import type { Route as _GenerateRoute } from '../pages/generate';
import type { Route as _OrderRoute } from '../pages/order';
import type { Route as _PreviewRoute } from '../pages/preview';
import type { Route as _ProductsRoute } from '../pages/products';
import type { Route as _UploadRoute } from '../pages/upload';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/designs': (typeof _DesignsRoute)['_inputType'];
    '/editor': (typeof _EditorRoute)['_inputType'];
    '/generate': (typeof _GenerateRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/order': (typeof _OrderRoute)['_inputType'];
    '/preview': (typeof _PreviewRoute)['_inputType'];
    '/products': (typeof _ProductsRoute)['_inputType'];
    '/upload': (typeof _UploadRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/designs': (typeof _DesignsRoute)['_outputType'];
    '/editor': (typeof _EditorRoute)['_outputType'];
    '/generate': (typeof _GenerateRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/order': (typeof _OrderRoute)['_outputType'];
    '/preview': (typeof _PreviewRoute)['_outputType'];
    '/products': (typeof _ProductsRoute)['_outputType'];
    '/upload': (typeof _UploadRoute)['_outputType'];
  }
}
