/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _DesignsRoute } from '../pages/designs';
import { Route as _EditorRoute } from '../pages/editor';
import { Route as _FaqRoute } from '../pages/faq';
import { Route as _IndexRoute } from '../pages/';
import { Route as _InquiryRoute } from '../pages/inquiry';
import { Route as _MyRoute } from '../pages/my';
import { Route as _OpenRoute } from '../pages/open';
import { Route as _OrderCompleteRoute } from '../pages/order-complete';
import { Route as _OrderDetailRoute } from '../pages/order-detail';
import { Route as _OrderRoute } from '../pages/order';
import { Route as _OrdersRoute } from '../pages/orders';
import { Route as _PreviewRoute } from '../pages/preview';
import { Route as _PrivacyRoute } from '../pages/privacy';
import { Route as _ProductsRoute } from '../pages/products';
import { Route as _TermsRoute } from '../pages/terms';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/designs': (typeof _DesignsRoute)['_inputType'];
    '/editor': (typeof _EditorRoute)['_inputType'];
    '/faq': (typeof _FaqRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/inquiry': (typeof _InquiryRoute)['_inputType'];
    '/my': (typeof _MyRoute)['_inputType'];
    '/open': (typeof _OpenRoute)['_inputType'];
    '/order-complete': (typeof _OrderCompleteRoute)['_inputType'];
    '/order-detail': (typeof _OrderDetailRoute)['_inputType'];
    '/order': (typeof _OrderRoute)['_inputType'];
    '/orders': (typeof _OrdersRoute)['_inputType'];
    '/preview': (typeof _PreviewRoute)['_inputType'];
    '/privacy': (typeof _PrivacyRoute)['_inputType'];
    '/products': (typeof _ProductsRoute)['_inputType'];
    '/terms': (typeof _TermsRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/designs': (typeof _DesignsRoute)['_outputType'];
    '/editor': (typeof _EditorRoute)['_outputType'];
    '/faq': (typeof _FaqRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/inquiry': (typeof _InquiryRoute)['_outputType'];
    '/my': (typeof _MyRoute)['_outputType'];
    '/open': (typeof _OpenRoute)['_outputType'];
    '/order-complete': (typeof _OrderCompleteRoute)['_outputType'];
    '/order-detail': (typeof _OrderDetailRoute)['_outputType'];
    '/order': (typeof _OrderRoute)['_outputType'];
    '/orders': (typeof _OrdersRoute)['_outputType'];
    '/preview': (typeof _PreviewRoute)['_outputType'];
    '/privacy': (typeof _PrivacyRoute)['_outputType'];
    '/products': (typeof _ProductsRoute)['_outputType'];
    '/terms': (typeof _TermsRoute)['_outputType'];
  }
}
